### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chdir '~' -> ''

### ISSUE THREAD

**Issue by adsjcsp** [atom-community/atom-ide-code-format#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Debian GNU/Linux
**Thrown From**: [atom-ide-code-format](https://github.com/atom-community/atom-ide-code-format) package 1.0.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, chdir '/home/adsjcsp' -> ''

```
At internal/process/main_thread_only.js:29

Error: ENOENT: no such file or directory, chdir '/home/adsjcsp' -> ''
    at process.chdir (internal/process/main_thread_only.js:29:13)
    at process.chdir (/app.asar/node_modules/graceful-fs/polyfills.js:20:9)
    at process.chdir (/packages/atom-ide-code-format/node_modules/graceful-fs/polyfills.js:22:11)
    at generateCommand (/packages/python-runner/lib/python-runner.js:70:10)
    at executePy (/packages/python-runner/lib/python-runner.js:103:12)
    at HTMLElement.pythonRunnerExecutePy (/packages/python-runner/lib/python-runner.js:144:38)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:352326)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:350801)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:786982)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:795036)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -9:23.2.0 core:backspace (input.hidden-input)
     -8:49.4.0 editor:move-to-first-character-of-line (input.hidden-input)
  4x -8:49 core:delete (input.hidden-input)
     -3:16.3.0 intentions:highlight (input.hidden-input)
     -3:16.1.0 core:select-all (input.hidden-input)
     -3:14.9.0 intentions:highlight (input.hidden-input)
     -3:13.1.0 code-format:format-code (input.hidden-input)
     -3:10.2.0 intentions:highlight (input.hidden-input)
     -0:29.7.0 outline:reveal-cursor (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:28 outline:show-call-hierarchy (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.1.0 python-runner:executePy (div.line)
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-python-run 0.9.7 
busy-signal 2.0.1 
ide-css 0.4.0 
ide-json 0.2.1 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
platformio-ide-terminal 2.10.1 
python-black 0.7.0 
python-runner 1.3.0 
terminal-tab 0.6.0 
```

**Comment by adsjcsp** [comment]
.
