### ISSUE TITLE
Failed to activate the atom-ide-code-format package

### ISSUE THREAD

**Issue by nfantano** [atom-community/atom-ide-code-format#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-ide-code-format](https://github.com/atom-community/atom-ide-code-format) package 1.0.2

### Stack Trace

Failed to activate the atom-ide-code-format package

```
At Cannot find module 'C:\Users\Nick\.atom\packages\atom-ide-code-format\node_modules\log4js\node_modules\debug\src\index.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\Nick\.atom\packages\atom-ide-code-format\node_modules\log4js\node_modules\debug\src\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/atom-ide-code-format/node_modules/log4js/lib/log4js.js:21:15)
    at /packages/atom-ide-code-format/node_modules/log4js/lib/log4js.js:158:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/atom-ide-code-format/dist/main.js:1:248)
    at /packages/atom-ide-code-format/dist/main.js:4:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508803)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
atom-python-run 0.9.7 
atom-typescript 14.3.2 
autocomplete-paths undefined 
busy-signal 2.0.1 
ide-html 0.7.0 
ide-php 0.7.18 
ide-python undefined 
intentions 2.1.1 
javascript-drag-import 0.1.13 
linter 3.4.0 
linter-eslint 8.6.6 
linter-ui-default 3.4.1 
php-cs-fixer 4.2.0 
```

**Comment by UziTech** [comment]
It seems like this is an install issue. Try uninstalling and reinstalling atom-ide-code-format

**Comment by JPRuehmann** [comment]
Disabling gives the message that there is no working packet like this.
